name: Build til.ashish.me

on:
  workflow_dispatch:
  push:
    branches:
    - master
    paths-ignore:
    - README.md

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@v2
      # We need full history to introspect created/updated:
      with:
        fetch-depth: 0  
        path: master
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - uses: actions/cache@v1
      name: Configure pip caching
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r master/requirements.txt
    - name: Build database
      run: |-
        cd master
        python build_database.py
    - name: Update README
      run: |-
        cd master
        python update_readme.py --rewrite
        cat README.md
    - name: Commit and push if README changed
      run: |-
        cd master
        git diff
        git config --global user.email "ashishsushilpatel@gmail.com"
        git config --global user.name "Ashish Patel"
        git diff --quiet || (git add * && git commit -m "chore: update README" && git push)
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Deploy Datasette using Zeit Now
      env:
        NOW_TOKEN: ${{ secrets.NOW_TOKEN }}
      run: |-
          cd master
          datasette publish vercel til.db \
            --token $NOW_TOKEN \
            --branch master \
            --project ashish-til \
            --metadata metadata.yaml \
            --static static:static \
            --install datasette-template-sql \
            --install "datasette-atom>=0.7" \
            --install datasette-json-html \
            --install beautifulsoup4 \
            --install datasette-debug-asgi \
            --install "datasette-graphql>=0.12" \
            --install datasette-media \
            --plugins-dir plugins \
            --template-dir templates \
            --public
